import './globals.css'
import 'remixicon/fonts/remixicon.css'

export const metadata = {
  title: 'TECH VILLA',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
<link rel="icon" href="/logo.png" sizes="any" />
      <body suppressHydrationWarning>{children}</body>
    </html>
  )
}
